In [1]:
!nvidia-smi

Mon Apr 14 07:06:10 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   51C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [2]:
!pip install --upgrade pip
!pip install cuml-cu12 --extra-index-url=https://pypi.nvidia.com

Requirement already satisfied: pip in /usr/local/lib/python3.11/dist-packages (25.0.1)
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Requirement already satisfied: cuml-cu12 in /usr/local/lib/python3.11/dist-packages (25.2.1)
Requirement already satisfied: cuda-python<13.0a0,>=12.6.2 in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (12.6.2.post1)
Requirement already satisfied: cudf-cu12==25.2.* in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (25.2.1)
Requirement already satisfied: cupy-cuda12x>=12.0.0 in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (13.3.0)
Requirement already satisfied: cuvs-cu12==25.2.* in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (25.2.1)
Requirement already satisfied: dask-cuda==25.2.* in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (25.2.0)
Requirement already satisfied: dask-cudf-cu12==25.2.* in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (25.2.2)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (1.4.2)
Requirement already satisfied: libcuml-cu12==25.2.* in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (25.2.1)
Requirement already satisfied: numba<0.61.0a0,>=0.59.1 in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (0.60.0)
Requirement already satisfied: numpy<3.0a0,>=1.23 in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (2.0.2)
Requirement already satisfied: nvidia-cublas-cu12 in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (12.5.3.2)
Requirement already satisfied: nvidia-cufft-cu12 in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (11.2.3.61)
Requirement already satisfied: nvidia-curand-cu12 in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (10.3.6.82)
Requirement already satisfied: nvidia-cusolver-cu12 in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (11.6.3.83)
Requirement already satisfied: nvidia-cusparse-cu12 in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (12.5.1.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (24.2)
Requirement already satisfied: pylibraft-cu12==25.2.* in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (25.2.0)
Requirement already satisfied: raft-dask-cu12==25.2.* in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (25.2.0)
Requirement already satisfied: rapids-dask-dependency==25.2.* in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (25.2.0)
Requirement already satisfied: rmm-cu12==25.2.* in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (25.2.0)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (1.14.1)
Requirement already satisfied: treelite==4.4.1 in /usr/local/lib/python3.11/dist-packages (from cuml-cu12) (4.4.1)
Requirement already satisfied: cachetools in /usr/local/lib/python3.11/dist-packages (from cudf-cu12==25.2.*->cuml-cu12) (5.5.2)
Requirement already satisfied: fsspec>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from cudf-cu12==25.2.*->cuml-cu12) (2025.3.2)
Requirement already satisfied: libcudf-cu12==25.2.* in /usr/local/lib/python3.11/dist-packages (from cudf-cu12==25.2.*->cuml-cu12) (25.2.1)
Requirement already satisfied: numba-cuda<0.3.0a0,>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from cudf-cu12==25.2.*->cuml-cu12) (0.2.0)
Requirement already satisfied: nvtx>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from cudf-cu12==25.2.*->cuml-cu12) (0.2.11)
Requirement already satisfied: pandas<2.2.4dev0,>=2.0 in /usr/local/lib/python3.11/dist-packages (from cudf-cu12==25.2.*->cuml-cu12) (2.2.2)
Requirement already satisfied: pyarrow<20.0.0a0,>=14.0.0 in /usr/local/lib/python3.11/dist-packages (from cudf-cu12==25.2.*->cuml-cu12) (18.1.0)
Requirement already satisfied: pylibcudf-cu12==25.2.* in /usr/local/lib/python3.11/dist-packages (from cudf-cu12==25.2.*->cuml-cu12) (25.2.1)
Requirement already satisfied: pynvjitlink-cu12 in /usr/local/lib/python3.11/dist-packages (from cudf-cu12==25.2.*->cuml-cu12) (0.5.2)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from cudf-cu12==25.2.*->cuml-cu12) (13.9.4)
Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from cudf-cu12==25.2.*->cuml-cu12) (4.13.1)
Requirement already satisfied: libcuvs-cu12==25.2.* in /usr/local/lib/python3.11/dist-packages (from cuvs-cu12==25.2.*->cuml-cu12) (25.2.1)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.11/dist-packages (from dask-cuda==25.2.*->cuml-cu12) (8.1.8)
Requirement already satisfied: pynvml<13.0.0a0,>=12.0.0 in /usr/local/lib/python3.11/dist-packages (from dask-cuda==25.2.*->cuml-cu12) (12.0.0)
Requirement already satisfied: zict>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from dask-cuda==25.2.*->cuml-cu12) (3.0.0)
Requirement already satisfied: libraft-cu12==25.2.* in /usr/local/lib/python3.11/dist-packages (from libcuml-cu12==25.2.*->cuml-cu12) (25.2.0)
Requirement already satisfied: distributed-ucxx-cu12==0.42.* in /usr/local/lib/python3.11/dist-packages (from raft-dask-cu12==25.2.*->cuml-cu12) (0.42.0)
Requirement already satisfied: ucx-py-cu12==0.42.* in /usr/local/lib/python3.11/dist-packages (from raft-dask-cu12==25.2.*->cuml-cu12) (0.42.0)
Requirement already satisfied: dask==2024.12.1 in /usr/local/lib/python3.11/dist-packages (from rapids-dask-dependency==25.2.*->cuml-cu12) (2024.12.1)
Requirement already satisfied: distributed==2024.12.1 in /usr/local/lib/python3.11/dist-packages (from rapids-dask-dependency==25.2.*->cuml-cu12) (2024.12.1)
Requirement already satisfied: dask-expr==1.1.21 in /usr/local/lib/python3.11/dist-packages (from rapids-dask-dependency==25.2.*->cuml-cu12) (1.1.21)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from dask==2024.12.1->rapids-dask-dependency==25.2.*->cuml-cu12) (3.1.1)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from dask==2024.12.1->rapids-dask-dependency==25.2.*->cuml-cu12) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.11/dist-packages (from dask==2024.12.1->rapids-dask-dependency==25.2.*->cuml-cu12) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from dask==2024.12.1->rapids-dask-dependency==25.2.*->cuml-cu12) (0.12.1)
Requirement already satisfied: importlib_metadata>=4.13.0 in /usr/local/lib/python3.11/dist-packages (from dask==2024.12.1->rapids-dask-dependency==25.2.*->cuml-cu12) (8.6.1)
Requirement already satisfied: jinja2>=2.10.3 in /usr/local/lib/python3.11/dist-packages (from distributed==2024.12.1->rapids-dask-dependency==25.2.*->cuml-cu12) (3.1.6)
Requirement already satisfied: locket>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from distributed==2024.12.1->rapids-dask-dependency==25.2.*->cuml-cu12) (1.0.0)
Requirement already satisfied: msgpack>=1.0.2 in /usr/local/lib/python3.11/dist-packages (from distributed==2024.12.1->rapids-dask-dependency==25.2.*->cuml-cu12) (1.1.0)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.11/dist-packages (from distributed==2024.12.1->rapids-dask-dependency==25.2.*->cuml-cu12) (5.9.5)
Requirement already satisfied: sortedcontainers>=2.0.5 in /usr/local/lib/python3.11/dist-packages (from distributed==2024.12.1->rapids-dask-dependency==25.2.*->cuml-cu12) (2.4.0)
Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from distributed==2024.12.1->rapids-dask-dependency==25.2.*->cuml-cu12) (3.1.0)
Requirement already satisfied: tornado>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from distributed==2024.12.1->rapids-dask-dependency==25.2.*->cuml-cu12) (6.4.2)
Requirement already satisfied: urllib3>=1.26.5 in /usr/local/lib/python3.11/dist-packages (from distributed==2024.12.1->rapids-dask-dependency==25.2.*->cuml-cu12) (2.3.0)
Requirement already satisfied: ucxx-cu12==0.42.* in /usr/local/lib/python3.11/dist-packages (from distributed-ucxx-cu12==0.42.*->raft-dask-cu12==25.2.*->cuml-cu12) (0.42.0)
Requirement already satisfied: libkvikio-cu12==25.2.* in /usr/local/lib/python3.11/dist-packages (from libcudf-cu12==25.2.*->cudf-cu12==25.2.*->cuml-cu12) (25.2.1)
Requirement already satisfied: nvidia-nvcomp-cu12==4.2.0.11 in /usr/local/lib/python3.11/dist-packages (from libcudf-cu12==25.2.*->cudf-cu12==25.2.*->cuml-cu12) (4.2.0.11)
Requirement already satisfied: libucx-cu12<1.19,>=1.15.0 in /usr/local/lib/python3.11/dist-packages (from ucx-py-cu12==0.42.*->raft-dask-cu12==25.2.*->cuml-cu12) (1.18.0)
Requirement already satisfied: libucxx-cu12==0.42.* in /usr/local/lib/python3.11/dist-packages (from ucxx-cu12==0.42.*->distributed-ucxx-cu12==0.42.*->raft-dask-cu12==25.2.*->cuml-cu12) (0.42.0)
Requirement already satisfied: fastrlock>=0.5 in /usr/local/lib/python3.11/dist-packages (from cupy-cuda12x>=12.0.0->cuml-cu12) (0.8.3)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba<0.61.0a0,>=0.59.1->cuml-cu12) (0.43.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.11/dist-packages (from nvidia-cufft-cu12->cuml-cu12) (12.5.82)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<2.2.4dev0,>=2.0->cudf-cu12==25.2.*->cuml-cu12) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<2.2.4dev0,>=2.0->cudf-cu12==25.2.*->cuml-cu12) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<2.2.4dev0,>=2.0->cudf-cu12==25.2.*->cuml-cu12) (2025.2)
Requirement already satisfied: nvidia-ml-py<13.0.0a0,>=12.0.0 in /usr/local/lib/python3.11/dist-packages (from pynvml<13.0.0a0,>=12.0.0->dask-cuda==25.2.*->cuml-cu12) (12.570.86)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->cudf-cu12==25.2.*->cuml-cu12) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->cudf-cu12==25.2.*->cuml-cu12) (2.18.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib_metadata>=4.13.0->dask==2024.12.1->rapids-dask-dependency==25.2.*->cuml-cu12) (3.21.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2>=2.10.3->distributed==2024.12.1->rapids-dask-dependency==25.2.*->cuml-cu12) (3.0.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->cudf-cu12==25.2.*->cuml-cu12) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<2.2.4dev0,>=2.0->cudf-cu12==25.2.*->cuml-cu12) (1.17.0)

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

In [4]:
import zipfile

with zipfile.ZipFile('archive.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/')

In [5]:
data = pd.read_csv("Travel.csv")

In [6]:
data.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [7]:
data['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [8]:
data['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [9]:
data['Gender'] = data["Gender"].replace('Fe Male', "Female")

In [10]:
data['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [11]:
data['ProductPitched'].value_counts()

ProductPitched
Basic           1842
Deluxe          1732
Standard         742
Super Deluxe     342
King             230
Name: count, dtype: int64

In [12]:
data['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [13]:
data['MaritalStatus'] = data["MaritalStatus"].replace('Single', "Unmarried")

In [14]:
data['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [15]:
data['Designation'].value_counts()

Designation
Executive         1842
Manager           1732
Senior Manager     742
AVP                342
VP                 230
Name: count, dtype: int64

In [16]:
data.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [17]:
null_features = [features for features in data.columns if data[features].isnull().sum()>=1]
for feature in null_features:
  print(feature, np.round(data[feature].isnull().mean()*100,5), '% missing values')

Age 4.62357 % missing values
TypeofContact 0.51146 % missing values
DurationOfPitch 5.13502 % missing values
NumberOfFollowups 0.92062 % missing values
PreferredPropertyStar 0.53191 % missing values
NumberOfTrips 2.86416 % missing values
NumberOfChildrenVisiting 1.35025 % missing values
MonthlyIncome 4.76678 % missing values

In [18]:
data[null_features].select_dtypes(exclude='object').describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

In [19]:
data['Age'].fillna(data['Age'].median(),inplace = True)

In [20]:
data['TypeofContact'].fillna(data['TypeofContact'].mode()[0],inplace = True)

In [21]:
data['DurationOfPitch'].fillna(data['DurationOfPitch'].median(),inplace = True)

In [22]:
data['NumberOfFollowups'].fillna(data['NumberOfFollowups'].mode()[0],inplace = True)

In [23]:
data['PreferredPropertyStar'].fillna(data['PreferredPropertyStar'].mode()[0],inplace = True)

In [24]:
data['NumberOfTrips'].fillna(data['NumberOfTrips'].median(),inplace = True)

In [25]:
data['NumberOfChildrenVisiting'].fillna(data['NumberOfChildrenVisiting'].mode()[0],inplace = True)

In [26]:
data['MonthlyIncome'].fillna(data['MonthlyIncome'].median(),inplace = True)

In [27]:
data.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [28]:
data.drop('CustomerID', inplace = True , axis=1)

In [29]:
data['TotalVisiting'] = data['NumberOfChildrenVisiting'] + data['NumberOfPersonVisiting']
data.drop(columns=['NumberOfChildrenVisiting','NumberOfPersonVisiting'],inplace=True, axis =1)

In [30]:
data.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [31]:
from sklearn.model_selection import train_test_split

X = data.drop('ProdTaken', axis=1)
y = data['ProdTaken']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
X_train.shape, X_test.shape

((3910, 17), (978, 17))

In [33]:
categorical_features = X.select_dtypes(include='object').columns
numerical_features = X.select_dtypes(exclude='object').columns

In [34]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer ##--> for combining multiple transformation technique(i always forgot this...)

numeric_transformer = StandardScaler()
onehot_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", onehot_transformer, categorical_features),
         ("StandardScaler", numeric_transformer, numerical_features),
    ]
)

In [35]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, ConfusionMatrixDisplay

In [37]:
%%time

model = RandomForestClassifier(n_estimators=100,min_samples_split=2,max_features= 8, max_depth = 15, n_jobs = -1)
model.fit(X_train, y_train)

# y_train_pred = model.predict(X_train)
# y_test_pred = model.predict(X_test)

# model_train_accuracy = accuracy_score(y_train, y_train_pred)
# model_train_precision = precision_score(y_train, y_train_pred)
# model_train_recall = recall_score(y_train, y_train_pred)
# model_train_f1 = f1_score(y_train, y_train_pred, average='weighted')
# model_train_roc_auc = roc_auc_score(y_train, y_train_pred)

# model_test_accuracy = accuracy_score(y_test, y_test_pred)
# model_test_precision = precision_score(y_test, y_test_pred)
# model_test_recall = recall_score(y_test, y_test_pred)
# model_test_f1 = f1_score(y_test, y_test_pred, average='weighted')
# model_test_roc_auc = roc_auc_score(y_test, y_test_pred)

CPU times: user 762 ms, sys: 40.2 ms, total: 802 ms
Wall time: 503 ms

RandomForestClassifier(max_depth=15, max_features=8, n_jobs=-1)

In [38]:
# print('Model performance Train set')
# print("- Accuracy: {:.4f}".format(model_train_accuracy))
# print('- Precision: {:.4f}'.format(model_train_precision))
# print('- Recall: {:.4f}'.format(model_train_recall))
# print('- F1 Score: {:.4f}'.format(model_train_f1))
# print('- ROC AUC Score: {:.4f}'.format(model_train_roc_auc))

# print('----------------------------------')

# print('Model performance Test set')
# print("- Accuracy: {:.4f}".format(model_test_accuracy))
# print('- Precision: {:.4f}'.format(model_test_precision))
# print('- Recall: {:.4f}'.format(model_test_recall))
# print('- F1 Score: {:.4f}'.format(model_test_f1))
# print('- ROC AUC Score: {:.4f}'.format(model_test_roc_auc))

In [39]:
%%time

model = RandomForestClassifier(n_estimators=500,min_samples_split=2,max_features= 8, max_depth = 15, n_jobs = -1)
model.fit(X_train, y_train)

# y_train_pred = model.predict(X_train)
# y_test_pred = model.predict(X_test)

CPU times: user 4 s, sys: 63.4 ms, total: 4.06 s
Wall time: 4.45 s

RandomForestClassifier(max_depth=15, max_features=8, n_estimators=500,
                       n_jobs=-1)

In [40]:
%%time

model = RandomForestClassifier(n_estimators=1000,min_samples_split=2,max_features= 8, max_depth = 30, n_jobs = -1)
model.fit(X_train, y_train)

# y_train_pred = model.predict(X_train)
# y_test_pred = model.predict(X_test)

# model_train_accuracy = accuracy_score(y_train, y_train_pred)
# model_train_precision = precision_score(y_train, y_train_pred)
# model_train_recall = recall_score(y_train, y_train_pred)
# model_train_f1 = f1_score(y_train, y_train_pred, average='weighted')
# model_train_roc_auc = roc_auc_score(y_train, y_train_pred)

# model_test_accuracy = accuracy_score(y_test, y_test_pred)
# model_test_precision = precision_score(y_test, y_test_pred)
# model_test_recall = recall_score(y_test, y_test_pred)
# model_test_f1 = f1_score(y_test, y_test_pred, average='weighted')
# model_test_roc_auc = roc_auc_score(y_test, y_test_pred)

CPU times: user 8.03 s, sys: 120 ms, total: 8.15 s
Wall time: 11.1 s

RandomForestClassifier(max_depth=30, max_features=8, n_estimators=1000,
                       n_jobs=-1)

In [41]:
# print('Model performance Train set')
# print("- Accuracy: {:.4f}".format(model_train_accuracy))
# print('- Precision: {:.4f}'.format(model_train_precision))
# print('- Recall: {:.4f}'.format(model_train_recall))
# print('- F1 Score: {:.4f}'.format(model_train_f1))
# print('- ROC AUC Score: {:.4f}'.format(model_train_roc_auc))

# print('----------------------------------')

# print('Model performance Test set')
# print("- Accuracy: {:.4f}".format(model_test_accuracy))
# print('- Precision: {:.4f}'.format(model_test_precision))
# print('- Recall: {:.4f}'.format(model_test_recall))
# print('- F1 Score: {:.4f}'.format(model_test_f1))
# print('- ROC AUC Score: {:.4f}'.format(model_test_roc_auc))

In [42]:
## cuML's accelerator mode

In [43]:
%load_ext cuml.accel

[2025-04-14 07:06:37.617] [CUML] [info] cuML: Installed accelerator for sklearn.
[2025-04-14 07:06:48.957] [CUML] [info] cuML: Installed accelerator for umap.
[2025-04-14 07:06:48.967] [CUML] [info] cuML: Installed accelerator for hdbscan.
[2025-04-14 07:06:48.967] [CUML] [info] cuML: Successfully initialized accelerator.

In [44]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, ConfusionMatrixDisplay

In [45]:
%%time

model = RandomForestClassifier(n_estimators=100,min_samples_split=2,max_features= 8, max_depth = 15, n_jobs = -1)
model.fit(X_train, y_train)

CPU times: user 301 ms, sys: 167 ms, total: 467 ms
Wall time: 379 ms

RandomForestClassifier(max_depth=15, max_features=8, n_jobs=-1)

In [46]:
%%time

model = RandomForestClassifier(n_estimators=500,min_samples_split=2,max_features= 8, max_depth = 15, n_jobs = -1)
model.fit(X_train, y_train)

# y_train_pred = model.predict(X_train)
# y_test_pred = model.predict(X_test)

CPU times: user 757 ms, sys: 349 ms, total: 1.11 s
Wall time: 733 ms

RandomForestClassifier(max_depth=15, max_features=8, n_estimators=500,
                       n_jobs=-1)

In [47]:
# %%time

# clf = RandomForestClassifier(n_estimators=500,min_samples_split=2,max_features= 8, max_depth = 15, n_jobs=-1)
# clf.fit(X_train, y_train)

In [48]:
y_pred = model.predict(X_test)
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.93      0.99      0.96       787
           1       0.96      0.70      0.81       191

    accuracy                           0.94       978
   macro avg       0.95      0.84      0.88       978
weighted avg       0.94      0.94      0.93       978

In [49]:
%%time

model = RandomForestClassifier(n_estimators=1000, max_depth=30, max_features= 8,min_samples_split=2, n_jobs=-1)
model.fit(X_train, y_train)

CPU times: user 1.89 s, sys: 759 ms, total: 2.65 s
Wall time: 1.73 s

RandomForestClassifier(max_depth=30, max_features=8, n_estimators=1000,
                       n_jobs=-1)

In [50]:
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.99      0.96       787
           1       0.96      0.71      0.81       191

    accuracy                           0.94       978
   macro avg       0.95      0.85      0.89       978
weighted avg       0.94      0.94      0.93       978